// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dsrhub.proto

package idl_dsrhub

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDSRRequest struct {
	Regulation           string   `protobuf:"bytes,1,opt,name=regulation,proto3" json:"regulation,omitempty"`
	StatusCallbackUrl    string   `protobuf:"bytes,2,opt,name=status_callback_url,json=statusCallbackUrl,proto3" json:"status_callback_url,omitempty"`
	SubjectRequestId     string   `protobuf:"bytes,3,opt,name=subject_request_id,json=subjectRequestId,proto3" json:"subject_request_id,omitempty"`
	SubjectRequestType   string   `protobuf:"bytes,4,opt,name=subject_request_type,json=subjectRequestType,proto3" json:"subject_request_type,omitempty"`
	IdentityType         string   `protobuf:"bytes,5,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,6,opt,name=identity_format,json=identityFormat,proto3" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,7,opt,name=identity_value,json=identityValue,proto3" json:"identity_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDSRRequest) Reset()         { *m = CreateDSRRequest{} }
func (m *CreateDSRRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDSRRequest) ProtoMessage()    {}
func (*CreateDSRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_872837866b3f167b, []int{0}
}

func (m *CreateDSRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRRequest.Unmarshal(m, b)
}
func (m *CreateDSRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRRequest.Marshal(b, m, deterministic)
}
func (m *CreateDSRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRRequest.Merge(m, src)
}
func (m *CreateDSRRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDSRRequest.Size(m)
}
func (m *CreateDSRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRRequest proto.InternalMessageInfo

func (m *CreateDSRRequest) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRRequest) GetStatusCallbackUrl() string {
	if m != nil {
		return m.StatusCallbackUrl
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

type CreateDSRResponse struct {
	Regulation           string   `protobuf:"bytes,1,opt,name=regulation,proto3" json:"regulation,omitempty"`
	RequestStatus        string   `protobuf:"bytes,2,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
	SubjectRequestId     string   `protobuf:"bytes,3,opt,name=subject_request_id,json=subjectRequestId,proto3" json:"subject_request_id,omitempty"`
	SubjectRequestType   string   `protobuf:"bytes,4,opt,name=subject_request_type,json=subjectRequestType,proto3" json:"subject_request_type,omitempty"`
	IdentityType         string   `protobuf:"bytes,5,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,6,opt,name=identity_format,json=identityFormat,proto3" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,7,opt,name=identity_value,json=identityValue,proto3" json:"identity_value,omitempty"`
	ControllerId         string   `protobuf:"bytes,8,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDSRResponse) Reset()         { *m = CreateDSRResponse{} }
func (m *CreateDSRResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDSRResponse) ProtoMessage()    {}
func (*CreateDSRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_872837866b3f167b, []int{1}
}

func (m *CreateDSRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRResponse.Unmarshal(m, b)
}
func (m *CreateDSRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRResponse.Marshal(b, m, deterministic)
}
func (m *CreateDSRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRResponse.Merge(m, src)
}
func (m *CreateDSRResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDSRResponse.Size(m)
}
func (m *CreateDSRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRResponse proto.InternalMessageInfo

func (m *CreateDSRResponse) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRResponse) GetRequestStatus() string {
	if m != nil {
		return m.RequestStatus
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

func (m *CreateDSRResponse) GetControllerId() string {
	if m != nil {
		return m.ControllerId
	}
	return ""
}

type ExchangeIdentityRequest struct {
	IdentityType         string   `protobuf:"bytes,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,2,opt,name=identity_format,json=identityFormat,proto3" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,3,opt,name=identity_value,json=identityValue,proto3" json:"identity_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeIdentityRequest) Reset()         { *m = ExchangeIdentityRequest{} }
func (m *ExchangeIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeIdentityRequest) ProtoMessage()    {}
func (*ExchangeIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_872837866b3f167b, []int{2}
}

func (m *ExchangeIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeIdentityRequest.Unmarshal(m, b)
}
func (m *ExchangeIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeIdentityRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeIdentityRequest.Merge(m, src)
}
func (m *ExchangeIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeIdentityRequest.Size(m)
}
func (m *ExchangeIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeIdentityRequest proto.InternalMessageInfo

func (m *ExchangeIdentityRequest) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *ExchangeIdentityRequest) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *ExchangeIdentityRequest) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

type ExchangeIdentityResponse struct {
	IdentityType         string   `protobuf:"bytes,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,2,opt,name=identity_format,json=identityFormat,proto3" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,3,opt,name=identity_value,json=identityValue,proto3" json:"identity_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeIdentityResponse) Reset()         { *m = ExchangeIdentityResponse{} }
func (m *ExchangeIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeIdentityResponse) ProtoMessage()    {}
func (*ExchangeIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_872837866b3f167b, []int{3}
}

func (m *ExchangeIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeIdentityResponse.Unmarshal(m, b)
}
func (m *ExchangeIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeIdentityResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeIdentityResponse.Merge(m, src)
}
func (m *ExchangeIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeIdentityResponse.Size(m)
}
func (m *ExchangeIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeIdentityResponse proto.InternalMessageInfo

func (m *ExchangeIdentityResponse) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *ExchangeIdentityResponse) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *ExchangeIdentityResponse) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDSRRequest)(nil), "idl.dsrhub.CreateDSRRequest")
	proto.RegisterType((*CreateDSRResponse)(nil), "idl.dsrhub.CreateDSRResponse")
	proto.RegisterType((*ExchangeIdentityRequest)(nil), "idl.dsrhub.ExchangeIdentityRequest")
	proto.RegisterType((*ExchangeIdentityResponse)(nil), "idl.dsrhub.ExchangeIdentityResponse")
}

func init() { proto.RegisterFile("dsrhub.proto", fileDescriptor_872837866b3f167b) }

var fileDescriptor_872837866b3f167b = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x65, 0x17, 0x0a, 0xbd, 0x6a, 0x4a, 0x3a, 0x20, 0x61, 0xa2, 0x52, 0x90, 0xd3, 0x08,
	0x54, 0x21, 0x07, 0xc1, 0xae, 0x4b, 0x5a, 0x10, 0xd9, 0x26, 0xc0, 0x82, 0x8d, 0x35, 0xb6, 0x2f,
	0xee, 0xc0, 0xd4, 0x63, 0xe6, 0xa7, 0x22, 0x5b, 0x90, 0x58, 0xc2, 0x82, 0x87, 0xe1, 0x41, 0xe0,
	0x11, 0x78, 0x10, 0x94, 0xf9, 0x49, 0x43, 0x4a, 0xa1, 0x3b, 0x24, 0x56, 0xb6, 0xce, 0xfd, 0x3c,
	0xf7, 0xcc, 0x99, 0x3b, 0x86, 0xf5, 0x4a, 0xc9, 0x43, 0x53, 0x64, 0xad, 0x14, 0x5a, 0x10, 0x60,
	0x15, 0xcf, 0x9c, 0xd2, 0xdb, 0xaa, 0x85, 0xa8, 0x39, 0x0e, 0x69, 0xcb, 0x86, 0xb4, 0x69, 0x84,
	0xa6, 0x9a, 0x89, 0x46, 0x39, 0x32, 0xfd, 0x1a, 0x43, 0x77, 0x5f, 0x22, 0xd5, 0x78, 0x30, 0x19,
	0x8f, 0xf1, 0xad, 0x41, 0xa5, 0xc9, 0x36, 0x80, 0xc4, 0xda, 0x70, 0x4b, 0x26, 0xd1, 0xed, 0xe8,
	0xee, 0xda, 0x78, 0x41, 0x21, 0x19, 0x5c, 0x55, 0x9a, 0x6a, 0xa3, 0xf2, 0x92, 0x72, 0x5e, 0xd0,
	0xf2, 0x4d, 0x6e, 0x24, 0x4f, 0x62, 0x0b, 0x6e, 0xba, 0xd2, 0xbe, 0xaf, 0x3c, 0x97, 0x9c, 0xdc,
	0x03, 0xa2, 0x4c, 0xf1, 0x1a, 0x4b, 0x9d, 0x4b, 0xd7, 0x22, 0x67, 0x55, 0xb2, 0x62, 0xf1, 0xae,
	0xaf, 0xf8, 0xde, 0xa3, 0x8a, 0xdc, 0x87, 0x6b, 0xcb, 0xb4, 0x9e, 0xb6, 0x98, 0x5c, 0xb0, 0x3c,
	0xf9, 0x95, 0x7f, 0x36, 0x6d, 0x91, 0xf4, 0xa1, 0xc3, 0x2a, 0x6c, 0x34, 0xd3, 0x53, 0x87, 0x5e,
	0xb4, 0xe8, 0x7a, 0x10, 0x2d, 0x74, 0x07, 0xae, 0xcc, 0xa1, 0x57, 0x42, 0x1e, 0x51, 0x9d, 0xac,
	0x5a, 0x6c, 0x23, 0xc8, 0x4f, 0xac, 0x4a, 0x06, 0x30, 0x57, 0xf2, 0x63, 0xca, 0x0d, 0x26, 0x97,
	0x2c, 0x37, 0xef, 0xf1, 0x62, 0x26, 0xa6, 0xdf, 0x63, 0xd8, 0x5c, 0x48, 0x4e, 0xb5, 0xa2, 0x51,
	0xf8, 0xd7, 0xe8, 0x06, 0xb0, 0x11, 0x36, 0xe5, 0x72, 0xf2, 0xa9, 0x75, 0xbc, 0x3a, 0xb1, 0xe2,
	0x7f, 0x99, 0xd8, 0xac, 0x69, 0x29, 0x1a, 0x2d, 0x05, 0xe7, 0x28, 0x67, 0xfb, 0xb9, 0xec, 0x9a,
	0x9e, 0x88, 0xa3, 0x2a, 0xfd, 0x14, 0xc1, 0xf5, 0xc7, 0xef, 0xca, 0x43, 0xda, 0xd4, 0x38, 0xf2,
	0x9f, 0x87, 0xb9, 0x3c, 0xe5, 0x3a, 0x3a, 0x9f, 0xeb, 0xf8, 0x9c, 0xae, 0x57, 0x7e, 0x77, 0xce,
	0x9f, 0x23, 0x48, 0x4e, 0x1b, 0xf2, 0xc7, 0xfd, 0x2f, 0x1c, 0x3d, 0xf8, 0x18, 0x43, 0xe7, 0x60,
	0x32, 0x7e, 0x6a, 0x8a, 0x09, 0xca, 0x63, 0x56, 0x22, 0x11, 0xb0, 0x36, 0x1f, 0x45, 0xb2, 0x95,
	0x9d, 0xdc, 0xfe, 0x6c, 0xf9, 0x6e, 0xf7, 0x6e, 0x9e, 0x51, 0x75, 0x1b, 0x4a, 0x07, 0xef, 0xbf,
	0xfd, 0xf8, 0x12, 0xdf, 0x4a, 0x7b, 0x43, 0x87, 0x0c, 0x4b, 0x8b, 0xe4, 0x95, 0x92, 0x61, 0xb6,
	0xf6, 0xa2, 0x5d, 0xf2, 0x21, 0x82, 0xee, 0x72, 0x28, 0xa4, 0xbf, 0xb8, 0xf4, 0x19, 0x67, 0xd8,
	0xdb, 0xf9, 0x33, 0xe4, 0x6d, 0xec, 0x58, 0x1b, 0xdb, 0xe9, 0x8d, 0x60, 0x03, 0x3d, 0x99, 0x87,
	0x28, 0xf6, 0xa2, 0xdd, 0x47, 0x83, 0x97, 0xfd, 0x9a, 0xe9, 0xd9, 0x42, 0xa5, 0x38, 0x0a, 0xa4,
	0x7f, 0xb0, 0x8a, 0xe7, 0xee, 0xb5, 0x58, 0xb5, 0xbf, 0xba, 0x87, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x09, 0xf8, 0xab, 0x24, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DSRHubServiceClient is the client API for DSRHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSRHubServiceClient interface {
	CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error)
	ExchangeIdentity(ctx context.Context, in *ExchangeIdentityRequest, opts ...grpc.CallOption) (*ExchangeIdentityResponse, error)
}

type dSRHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSRHubServiceClient(cc grpc.ClientConnInterface) DSRHubServiceClient {
	return &dSRHubServiceClient{cc}
}

func (c *dSRHubServiceClient) CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error) {
	out := new(CreateDSRResponse)
	err := c.cc.Invoke(ctx, "/idl.dsrhub.DSRHubService/CreateDSR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSRHubServiceClient) ExchangeIdentity(ctx context.Context, in *ExchangeIdentityRequest, opts ...grpc.CallOption) (*ExchangeIdentityResponse, error) {
	out := new(ExchangeIdentityResponse)
	err := c.cc.Invoke(ctx, "/idl.dsrhub.DSRHubService/ExchangeIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSRHubServiceServer is the server API for DSRHubService service.
type DSRHubServiceServer interface {
	CreateDSR(context.Context, *CreateDSRRequest) (*CreateDSRResponse, error)
	ExchangeIdentity(context.Context, *ExchangeIdentityRequest) (*ExchangeIdentityResponse, error)
}

// UnimplementedDSRHubServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDSRHubServiceServer struct {
}

func (*UnimplementedDSRHubServiceServer) CreateDSR(ctx context.Context, req *CreateDSRRequest) (*CreateDSRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDSR not implemented")
}
func (*UnimplementedDSRHubServiceServer) ExchangeIdentity(ctx context.Context, req *ExchangeIdentityRequest) (*ExchangeIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeIdentity not implemented")
}

func RegisterDSRHubServiceServer(s *grpc.Server, srv DSRHubServiceServer) {
	s.RegisterService(&_DSRHubService_serviceDesc, srv)
}

func _DSRHubService_CreateDSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSRHubServiceServer).CreateDSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.dsrhub.DSRHubService/CreateDSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSRHubServiceServer).CreateDSR(ctx, req.(*CreateDSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSRHubService_ExchangeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSRHubServiceServer).ExchangeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.dsrhub.DSRHubService/ExchangeIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSRHubServiceServer).ExchangeIdentity(ctx, req.(*ExchangeIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSRHubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.dsrhub.DSRHubService",
	HandlerType: (*DSRHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDSR",
			Handler:    _DSRHubService_CreateDSR_Handler,
		},
		{
			MethodName: "ExchangeIdentity",
			Handler:    _DSRHubService_ExchangeIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsrhub.proto",
}
