swagger: '2.0'
info:
  description: >
    DSRHub OpenDSR is a simplified version of the OpenDSR specification.
  version: 2.0.0
  title: OpenDSR - OpenAPI v2
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /opendsr

# tags are used for organizing operations
tags:
- name: Data Controller
  description: Data Controller (GDPR) / Business (CCPA)
- name: Data Processor
  description: Data Processor (GDPR) / Vendor (CCPA)

schemes:
- http
- https

consumes:
  - application/json
produces:
  - application/json

paths:
  /requests:
    post:
      tags:
      - Data Processor
      summary: Post a OpenDSR request
      operationId: postRequests
      description: |
        OpenDSR service implementations MUST provide an endpoint that creates OpenDSR JSON requests via HTTP POST.
        Controllers MUST submit requests with the following parameters.
      parameters:
        - in: body
          name: request
          schema:
            type: object
            properties:
              api_version:
                $ref: '#/definitions/ApiVersion'
              regulation:
                type: string
                description: |
                  string value representing the regulation that this request is covered by: 'gdpr' or 'ccpa' are currently supported.
                enum:
                  - gdpr
                  - ccpa
                example: gdpr
              subject_request_id:
                type: string
                description: |
                  UUID v4 string. This MUST be generated by the Controller at the time of request submission to a Processor.
                example: a7551968-d5d6-44b2-9831-815ac9017798
              subject_request_type:
                $ref: '#/definitions/SubjectRequestType'
              subject_identities:
                type: array
                description: array of Identity objects
                items:
                  $ref: '#/definitions/Identity'
              status_callback_urls:
                type: array
                items:
                  type: string
                example: https://examplecontroller.com/opendsr/callbacks
      responses:
        201:
          description: request created
          headers:
            X-OpenDSR-Processor-Domain:
              type: string
              description: header representing the domain for which the signing certificate is issued. The domain name MUST match the domain on which OpenDSR requests are received
            X-OpenDSR-Signature:
              type: string
              description: header Base64 encoded signature generated by a certificate matching the domain in the X-OpenDSR-Processor-Domain header.
          schema:
            type: object
            properties:
              api_version:
                $ref: '#/definitions/ApiVersion'
              regulation:
                type: string
                description: |
                  string value representing the regulation that this request is covered by: 'gdpr' or 'ccpa' are currently supported.
                enum:
                  - gdpr
                  - ccpa
                example: gdpr
              subject_request_id:
                type: string
                description: |
                  UUID v4 string. This MUST be generated by the Controller at the time of request submission to a Processor.
                example: a7551968-d5d6-44b2-9831-815ac9017798
              subject_request_type:
                $ref: '#/definitions/SubjectRequestType'
              subject_identities:
                type: array
                description: array of Identity objects
                items:
                  $ref: '#/definitions/Identity'
              controller_id:
                type: string
                description: string indicating the unique identity of the Controller in the Processor’s system.
                example: example_controller_id
              request_status:
                type: string
                description: string indicating the status of the request as defined in section 8.
                enum: [pending, in_progress, completed, cancelled]
                example: pending
        400:
          $ref: '#/definitions/Error'
        403:
          $ref: '#/definitions/Error'
        500:
          $ref: '#/definitions/Error'

  /callbacks:
    post:
      tags:
      - Data Controller
      summary: OpenDSR callbacks
      operationId: postCallbacks
      description: Processor reports status to the Controller via callbacks
      parameters:
        - in: header
          name: X-OpenDSR-Processor-Domain
          type: string
          description: header representing the domain for which the signing certificate is issued. The domain name MUST match the domain on which OpenDSR requests are received.
        - in: header
          name: X-OpenDSR-Signature
          type: string
          description: header Base64 encoded signature generated by a certificate matching the domain in the X-OpenDSR-Processor-Domain header.
        - in: body
          name: request
          schema:
            type: object
            properties:
              api_version:
                $ref: '#/definitions/ApiVersion'
              regulation:
                type: string
                description: |
                  string value representing the regulation that this request is covered by: 'gdpr' or 'ccpa' are currently supported.
                enum:
                  - gdpr
                  - ccpa
                example: gdpr
              subject_request_id:
                type: string
                description: |
                  UUID v4 string. This MUST be generated by the Controller at the time of request submission to a Processor.
                example: a7551968-d5d6-44b2-9831-815ac9017798
              subject_request_type:
                $ref: '#/definitions/SubjectRequestType'
              subject_identities:
                type: array
                description: array of Identity objects
                items:
                  $ref: '#/definitions/Identity'
              controller_id:
                type: string
                description: string indicating the unique identity of the Controller in the Processor’s system.
                example: example_controller_id
              request_status:
                type: string
                description: string indicating the status of the request as defined in section 8.
                enum: [pending, in_progress, completed, cancelled]
                example: pending
      responses:
        201:
          description: OK response for the callbacks
          schema:
            type: string
            example: "OK"
        400:
          $ref: '#/definitions/Error'
        403:
          $ref: '#/definitions/Error'
        500:
          $ref: '#/definitions/Error'

definitions:
  ApiVersion:
    type: string
    example: "2.0"
  SubjectRequestType:
    type: string
    description: |
      string value representing the type of OpenDSR Request. Supported values: "erasure", "portability", "access"
    enum: [access, portability, erasure]
    example: erasure
  Identity:
    type: object
    properties:
      identity_type:
        type: string
        description: string value representing the form of identity.
        enum:
          - android_advertising_id
          - android_id
          - controller_customer_id
          - email
          - fire_advertising_id
          - ios_advertising_id
          - ios_vendor_id
          - microsoft_advertising_id
          - microsoft_publisher_id
          - roku_advertising_id
          - roku_publisher_id
        example: email
      idemtity_format:
        type: string
        description: string value representing the encoding of the identity
        enum:
          - md5
          - raw
          - sha1
          - sha256
        example: raw
      identity_value:
        type: string
        description: string value representing the identity.
        example: johndoe@example.com
  Error:
    type: object
    properties:
      error:
        type: string
        description: String description of the issue that was encountered.
        example: subject_request_id field is required.
