// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opendsr/opendsr.proto

package opendsr // import "github.com/dsrhub/dsrhub/proto/dsrhub/opendsr"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identity struct {
	IdentityType         string   `protobuf:"bytes,1,opt,name=identity_type,json=identityType" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,2,opt,name=identity_format,json=identityFormat" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,3,opt,name=identity_value,json=identityValue" json:"identity_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_opendsr_a2b7d907e0a901c6, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (dst *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(dst, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *Identity) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *Identity) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

type CreateDSRRequest struct {
	ApiVersion           string      `protobuf:"bytes,1,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Regulation           string      `protobuf:"bytes,2,opt,name=regulation" json:"regulation,omitempty"`
	SubjectRequestId     string      `protobuf:"bytes,3,opt,name=subject_request_id,json=subjectRequestId" json:"subject_request_id,omitempty"`
	SubjectRequestType   string      `protobuf:"bytes,4,opt,name=subject_request_type,json=subjectRequestType" json:"subject_request_type,omitempty"`
	SubjectIdentities    []*Identity `protobuf:"bytes,5,rep,name=subject_identities,json=subjectIdentities" json:"subject_identities,omitempty"`
	StatusCallbackUrls   []string    `protobuf:"bytes,6,rep,name=status_callback_urls,json=statusCallbackUrls" json:"status_callback_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateDSRRequest) Reset()         { *m = CreateDSRRequest{} }
func (m *CreateDSRRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDSRRequest) ProtoMessage()    {}
func (*CreateDSRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_opendsr_a2b7d907e0a901c6, []int{1}
}
func (m *CreateDSRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRRequest.Unmarshal(m, b)
}
func (m *CreateDSRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDSRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRRequest.Merge(dst, src)
}
func (m *CreateDSRRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDSRRequest.Size(m)
}
func (m *CreateDSRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRRequest proto.InternalMessageInfo

func (m *CreateDSRRequest) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *CreateDSRRequest) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectIdentities() []*Identity {
	if m != nil {
		return m.SubjectIdentities
	}
	return nil
}

func (m *CreateDSRRequest) GetStatusCallbackUrls() []string {
	if m != nil {
		return m.StatusCallbackUrls
	}
	return nil
}

type CreateDSRResponse struct {
	ApiVersion           string      `protobuf:"bytes,1,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Regulation           string      `protobuf:"bytes,2,opt,name=regulation" json:"regulation,omitempty"`
	SubjectRequestId     string      `protobuf:"bytes,3,opt,name=subject_request_id,json=subjectRequestId" json:"subject_request_id,omitempty"`
	SubjectRequestType   string      `protobuf:"bytes,4,opt,name=subject_request_type,json=subjectRequestType" json:"subject_request_type,omitempty"`
	SubjectIdentities    []*Identity `protobuf:"bytes,5,rep,name=subject_identities,json=subjectIdentities" json:"subject_identities,omitempty"`
	ControllerId         string      `protobuf:"bytes,6,opt,name=controller_id,json=controllerId" json:"controller_id,omitempty"`
	RequestStatus        string      `protobuf:"bytes,7,opt,name=request_status,json=requestStatus" json:"request_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateDSRResponse) Reset()         { *m = CreateDSRResponse{} }
func (m *CreateDSRResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDSRResponse) ProtoMessage()    {}
func (*CreateDSRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_opendsr_a2b7d907e0a901c6, []int{2}
}
func (m *CreateDSRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRResponse.Unmarshal(m, b)
}
func (m *CreateDSRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDSRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRResponse.Merge(dst, src)
}
func (m *CreateDSRResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDSRResponse.Size(m)
}
func (m *CreateDSRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRResponse proto.InternalMessageInfo

func (m *CreateDSRResponse) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *CreateDSRResponse) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectIdentities() []*Identity {
	if m != nil {
		return m.SubjectIdentities
	}
	return nil
}

func (m *CreateDSRResponse) GetControllerId() string {
	if m != nil {
		return m.ControllerId
	}
	return ""
}

func (m *CreateDSRResponse) GetRequestStatus() string {
	if m != nil {
		return m.RequestStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*Identity)(nil), "dsrhub.opendsr.Identity")
	proto.RegisterType((*CreateDSRRequest)(nil), "dsrhub.opendsr.CreateDSRRequest")
	proto.RegisterType((*CreateDSRResponse)(nil), "dsrhub.opendsr.CreateDSRResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpenDSRServiceClient is the client API for OpenDSRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpenDSRServiceClient interface {
	CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error)
}

type openDSRServiceClient struct {
	cc *grpc.ClientConn
}

func NewOpenDSRServiceClient(cc *grpc.ClientConn) OpenDSRServiceClient {
	return &openDSRServiceClient{cc}
}

func (c *openDSRServiceClient) CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error) {
	out := new(CreateDSRResponse)
	err := c.cc.Invoke(ctx, "/dsrhub.opendsr.OpenDSRService/CreateDSR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenDSRServiceServer is the server API for OpenDSRService service.
type OpenDSRServiceServer interface {
	CreateDSR(context.Context, *CreateDSRRequest) (*CreateDSRResponse, error)
}

func RegisterOpenDSRServiceServer(s *grpc.Server, srv OpenDSRServiceServer) {
	s.RegisterService(&_OpenDSRService_serviceDesc, srv)
}

func _OpenDSRService_CreateDSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenDSRServiceServer).CreateDSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsrhub.opendsr.OpenDSRService/CreateDSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenDSRServiceServer).CreateDSR(ctx, req.(*CreateDSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenDSRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dsrhub.opendsr.OpenDSRService",
	HandlerType: (*OpenDSRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDSR",
			Handler:    _OpenDSRService_CreateDSR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opendsr/opendsr.proto",
}

func init() { proto.RegisterFile("opendsr/opendsr.proto", fileDescriptor_opendsr_a2b7d907e0a901c6) }

var fileDescriptor_opendsr_a2b7d907e0a901c6 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x93, 0x4f, 0xae, 0xd3, 0x30,
	0x10, 0xc6, 0xf5, 0x5a, 0x28, 0xbc, 0x79, 0xb4, 0xb4, 0x16, 0x48, 0x11, 0x0b, 0x08, 0xad, 0x10,
	0x5d, 0x40, 0x8a, 0xca, 0x0d, 0x68, 0x05, 0xca, 0x0a, 0x94, 0x40, 0x17, 0x6c, 0x22, 0x27, 0x19,
	0x8a, 0xc1, 0x8d, 0x8d, 0xed, 0x54, 0xea, 0x8a, 0x1b, 0x71, 0x0f, 0x6e, 0x85, 0x62, 0x3b, 0xe9,
	0x9f, 0x05, 0x17, 0x78, 0x2b, 0x27, 0xbf, 0xf9, 0xec, 0xf9, 0xfc, 0x65, 0x02, 0x8f, 0x85, 0xc4,
	0xaa, 0xd4, 0x6a, 0xe1, 0xd7, 0x48, 0x2a, 0x61, 0x04, 0x19, 0x95, 0x5a, 0x7d, 0xaf, 0xf3, 0xc8,
	0xd3, 0xe9, 0x6f, 0xb8, 0x1f, 0x97, 0x58, 0x19, 0x66, 0x0e, 0x64, 0x06, 0x43, 0xe6, 0x9f, 0x33,
	0x73, 0x90, 0x18, 0x5c, 0x85, 0x57, 0xf3, 0xeb, 0xe4, 0x41, 0x0b, 0x3f, 0x1f, 0x24, 0x92, 0x97,
	0xf0, 0xb0, 0x13, 0x7d, 0x13, 0x6a, 0x47, 0x4d, 0xd0, 0xb3, 0xb2, 0x51, 0x8b, 0xdf, 0x5b, 0x4a,
	0x5e, 0x40, 0x47, 0xb2, 0x3d, 0xe5, 0x35, 0x06, 0x7d, 0xab, 0xeb, 0x7a, 0x6c, 0x1a, 0x38, 0xfd,
	0xd3, 0x83, 0xf1, 0x4a, 0x21, 0x35, 0xb8, 0x4e, 0x93, 0x04, 0x7f, 0xd5, 0xa8, 0x0d, 0x79, 0x06,
	0x37, 0x54, 0xb2, 0x6c, 0x8f, 0x4a, 0x33, 0x51, 0x79, 0x1f, 0x40, 0x25, 0xdb, 0x38, 0x42, 0x9e,
	0x02, 0x28, 0xdc, 0xd6, 0x9c, 0x9a, 0xa6, 0xee, 0x0c, 0x9c, 0x10, 0xf2, 0x0a, 0x88, 0xae, 0xf3,
	0x1f, 0x58, 0x98, 0x4c, 0xb9, 0x33, 0x33, 0x56, 0x7a, 0x03, 0x63, 0x5f, 0xf1, 0xcd, 0xe2, 0x92,
	0xbc, 0x81, 0x47, 0x97, 0x6a, 0x7b, 0xff, 0x3b, 0x56, 0x4f, 0xce, 0xf5, 0x36, 0x85, 0x0f, 0xc7,
	0xf3, 0xfd, 0x75, 0x18, 0xea, 0xe0, 0x6e, 0xd8, 0x9f, 0xdf, 0x2c, 0x83, 0xe8, 0x3c, 0xe3, 0xa8,
	0x0d, 0x38, 0x99, 0xf8, 0x3d, 0x71, 0xb7, 0xc5, 0xb6, 0x36, 0xd4, 0xd4, 0x3a, 0x2b, 0x28, 0xe7,
	0x39, 0x2d, 0x7e, 0x66, 0xb5, 0xe2, 0x3a, 0x18, 0x84, 0x7d, 0xdb, 0xda, 0xd6, 0x56, 0xbe, 0xf4,
	0x45, 0x71, 0x3d, 0xfd, 0xdb, 0x83, 0xc9, 0x49, 0x60, 0x5a, 0x8a, 0x4a, 0xe3, 0x2d, 0x4a, 0x6c,
	0x06, 0xc3, 0x42, 0x54, 0x46, 0x09, 0xce, 0x51, 0x35, 0x1e, 0x07, 0x6e, 0x4a, 0x8f, 0x30, 0x2e,
	0x9b, 0xe1, 0x6b, 0x7d, 0xb9, 0x08, 0x83, 0x7b, 0x6e, 0xf8, 0x3c, 0x4d, 0x2d, 0x5c, 0xe6, 0x30,
	0xfa, 0x28, 0xb1, 0x5a, 0xa7, 0x49, 0x8a, 0x6a, 0xcf, 0x0a, 0x24, 0x9f, 0xe0, 0xba, 0x0b, 0x97,
	0x84, 0x97, 0xbe, 0x2e, 0x07, 0xf5, 0xc9, 0xf3, 0xff, 0x28, 0xdc, 0x97, 0x79, 0xb7, 0xf8, 0xfa,
	0x7a, 0xcb, 0x4c, 0xa3, 0x29, 0xc4, 0x6e, 0xe1, 0xe4, 0xed, 0x62, 0xff, 0xc9, 0xf6, 0xc5, 0x1f,
	0x91, 0x0f, 0x2c, 0x7d, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x3f, 0x38, 0x5d, 0xc2, 0x03,
	0x00, 0x00,
}
