// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opendsr/opendsr.proto

package opendsr // import "github.com/dsrhub/dsrhub/proto/dsrhub/opendsr"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateDSRRequest struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Regulation           string   `protobuf:"bytes,2,opt,name=regulation" json:"regulation,omitempty"`
	StatusCallbackUrl    string   `protobuf:"bytes,3,opt,name=status_callback_url,json=statusCallbackUrl" json:"status_callback_url,omitempty"`
	SubjectRequestId     string   `protobuf:"bytes,4,opt,name=subject_request_id,json=subjectRequestId" json:"subject_request_id,omitempty"`
	SubjectRequestType   string   `protobuf:"bytes,5,opt,name=subject_request_type,json=subjectRequestType" json:"subject_request_type,omitempty"`
	IdentityType         string   `protobuf:"bytes,6,opt,name=identity_type,json=identityType" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,7,opt,name=identity_format,json=identityFormat" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,8,opt,name=identity_value,json=identityValue" json:"identity_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDSRRequest) Reset()         { *m = CreateDSRRequest{} }
func (m *CreateDSRRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDSRRequest) ProtoMessage()    {}
func (*CreateDSRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_opendsr_fa2e06da0c4a0cd5, []int{0}
}
func (m *CreateDSRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRRequest.Unmarshal(m, b)
}
func (m *CreateDSRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDSRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRRequest.Merge(dst, src)
}
func (m *CreateDSRRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDSRRequest.Size(m)
}
func (m *CreateDSRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRRequest proto.InternalMessageInfo

func (m *CreateDSRRequest) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *CreateDSRRequest) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRRequest) GetStatusCallbackUrl() string {
	if m != nil {
		return m.StatusCallbackUrl
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRRequest) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *CreateDSRRequest) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

type CreateDSRResponse struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Regulation           string   `protobuf:"bytes,2,opt,name=regulation" json:"regulation,omitempty"`
	RequestStatus        string   `protobuf:"bytes,3,opt,name=request_status,json=requestStatus" json:"request_status,omitempty"`
	SubjectRequestId     string   `protobuf:"bytes,4,opt,name=subject_request_id,json=subjectRequestId" json:"subject_request_id,omitempty"`
	SubjectRequestType   string   `protobuf:"bytes,5,opt,name=subject_request_type,json=subjectRequestType" json:"subject_request_type,omitempty"`
	IdentityType         string   `protobuf:"bytes,6,opt,name=identity_type,json=identityType" json:"identity_type,omitempty"`
	IdentityFormat       string   `protobuf:"bytes,7,opt,name=identity_format,json=identityFormat" json:"identity_format,omitempty"`
	IdentityValue        string   `protobuf:"bytes,8,opt,name=identity_value,json=identityValue" json:"identity_value,omitempty"`
	ControllerId         string   `protobuf:"bytes,9,opt,name=controller_id,json=controllerId" json:"controller_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDSRResponse) Reset()         { *m = CreateDSRResponse{} }
func (m *CreateDSRResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDSRResponse) ProtoMessage()    {}
func (*CreateDSRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_opendsr_fa2e06da0c4a0cd5, []int{1}
}
func (m *CreateDSRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDSRResponse.Unmarshal(m, b)
}
func (m *CreateDSRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDSRResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDSRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDSRResponse.Merge(dst, src)
}
func (m *CreateDSRResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDSRResponse.Size(m)
}
func (m *CreateDSRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDSRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDSRResponse proto.InternalMessageInfo

func (m *CreateDSRResponse) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *CreateDSRResponse) GetRegulation() string {
	if m != nil {
		return m.Regulation
	}
	return ""
}

func (m *CreateDSRResponse) GetRequestStatus() string {
	if m != nil {
		return m.RequestStatus
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestId() string {
	if m != nil {
		return m.SubjectRequestId
	}
	return ""
}

func (m *CreateDSRResponse) GetSubjectRequestType() string {
	if m != nil {
		return m.SubjectRequestType
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityFormat() string {
	if m != nil {
		return m.IdentityFormat
	}
	return ""
}

func (m *CreateDSRResponse) GetIdentityValue() string {
	if m != nil {
		return m.IdentityValue
	}
	return ""
}

func (m *CreateDSRResponse) GetControllerId() string {
	if m != nil {
		return m.ControllerId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDSRRequest)(nil), "dsrhub.opendsr.CreateDSRRequest")
	proto.RegisterType((*CreateDSRResponse)(nil), "dsrhub.opendsr.CreateDSRResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpenDSRServiceClient is the client API for OpenDSRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpenDSRServiceClient interface {
	CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error)
}

type openDSRServiceClient struct {
	cc *grpc.ClientConn
}

func NewOpenDSRServiceClient(cc *grpc.ClientConn) OpenDSRServiceClient {
	return &openDSRServiceClient{cc}
}

func (c *openDSRServiceClient) CreateDSR(ctx context.Context, in *CreateDSRRequest, opts ...grpc.CallOption) (*CreateDSRResponse, error) {
	out := new(CreateDSRResponse)
	err := c.cc.Invoke(ctx, "/dsrhub.opendsr.OpenDSRService/CreateDSR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenDSRServiceServer is the server API for OpenDSRService service.
type OpenDSRServiceServer interface {
	CreateDSR(context.Context, *CreateDSRRequest) (*CreateDSRResponse, error)
}

func RegisterOpenDSRServiceServer(s *grpc.Server, srv OpenDSRServiceServer) {
	s.RegisterService(&_OpenDSRService_serviceDesc, srv)
}

func _OpenDSRService_CreateDSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenDSRServiceServer).CreateDSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dsrhub.opendsr.OpenDSRService/CreateDSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenDSRServiceServer).CreateDSR(ctx, req.(*CreateDSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenDSRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dsrhub.opendsr.OpenDSRService",
	HandlerType: (*OpenDSRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDSR",
			Handler:    _OpenDSRService_CreateDSR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opendsr/opendsr.proto",
}

func init() { proto.RegisterFile("opendsr/opendsr.proto", fileDescriptor_opendsr_fa2e06da0c4a0cd5) }

var fileDescriptor_opendsr_fa2e06da0c4a0cd5 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0xd5, 0x02, 0x85, 0x7e, 0xd0, 0xd0, 0x1a, 0x90, 0x22, 0x0e, 0x50, 0x8a, 0x2a, 0x38,
	0x40, 0x8a, 0xe0, 0x1f, 0xd0, 0x0a, 0xa9, 0x27, 0x50, 0xc2, 0x7a, 0xd8, 0x25, 0x72, 0x92, 0x6f,
	0x9d, 0x37, 0x37, 0xf6, 0x6c, 0xa7, 0x52, 0xff, 0xe9, 0xfe, 0xc8, 0xee, 0x53, 0x6c, 0x27, 0x5d,
	0x7b, 0xd8, 0x65, 0xb7, 0x9d, 0xac, 0x3e, 0xef, 0xa3, 0x7e, 0xf6, 0xeb, 0x18, 0xde, 0x09, 0x89,
	0x65, 0xa1, 0xd5, 0xcc, 0xaf, 0x91, 0x54, 0xc2, 0x08, 0x12, 0x14, 0x5a, 0x9d, 0x57, 0x59, 0xe4,
	0xe9, 0xe4, 0xba, 0x0b, 0xc3, 0xb9, 0x42, 0x6a, 0x70, 0x91, 0xc4, 0x31, 0x5e, 0x55, 0xa8, 0x0d,
	0xf9, 0x08, 0x2f, 0xa9, 0x64, 0xe9, 0x16, 0x95, 0x66, 0xa2, 0x0c, 0x3b, 0xe3, 0xce, 0xd7, 0x7e,
	0x0c, 0x54, 0xb2, 0x95, 0x23, 0xe4, 0x03, 0x80, 0xc2, 0x75, 0xc5, 0xa9, 0xa9, 0xf3, 0xae, 0xcb,
	0xf7, 0x84, 0x44, 0xf0, 0x46, 0x1b, 0x6a, 0x2a, 0x9d, 0xe6, 0x94, 0xf3, 0x8c, 0xe6, 0x97, 0x69,
	0xa5, 0x78, 0xf8, 0xc4, 0x8a, 0x23, 0x17, 0xcd, 0x7d, 0x72, 0xa2, 0x38, 0xf9, 0x06, 0x44, 0x57,
	0xd9, 0x05, 0xe6, 0x26, 0x55, 0x6e, 0x0f, 0x29, 0x2b, 0xc2, 0xa7, 0x56, 0x1f, 0xfa, 0xc4, 0x6f,
	0x6e, 0x59, 0x90, 0x1f, 0xf0, 0xf6, 0xd8, 0x36, 0x3b, 0x89, 0xe1, 0x33, 0xeb, 0x93, 0x43, 0xff,
	0xff, 0x4e, 0x22, 0xf9, 0x0c, 0x03, 0x56, 0x60, 0x69, 0x98, 0xd9, 0x39, 0xb5, 0x67, 0xd5, 0x57,
	0x0d, 0xb4, 0xd2, 0x17, 0x78, 0xdd, 0x4a, 0x67, 0x42, 0x6d, 0xa8, 0x09, 0x9f, 0x5b, 0x2d, 0x68,
	0xf0, 0x1f, 0x4b, 0xc9, 0x14, 0x5a, 0x92, 0x6e, 0x29, 0xaf, 0x30, 0x7c, 0x61, 0xbd, 0x76, 0xc6,
	0xaa, 0x86, 0x93, 0x9b, 0x2e, 0x8c, 0xee, 0x54, 0xab, 0xa5, 0x28, 0x35, 0x3e, 0xbc, 0xdb, 0x29,
	0x04, 0xcd, 0xa9, 0x5d, 0x91, 0xbe, 0xd6, 0x81, 0xa7, 0x89, 0x85, 0x8f, 0xb2, 0xd2, 0x7a, 0x68,
	0x2e, 0x4a, 0xa3, 0x04, 0xe7, 0xa8, 0xea, 0xf3, 0xf4, 0xdd, 0xd0, 0x3d, 0x5c, 0x16, 0x3f, 0x33,
	0x08, 0xfe, 0x4a, 0x2c, 0x17, 0x49, 0x9c, 0xa0, 0xda, 0xb2, 0x1c, 0xc9, 0x3f, 0xe8, 0xb7, 0x17,
	0x41, 0xc6, 0xd1, 0xe1, 0x13, 0x88, 0x8e, 0x3f, 0xff, 0xf7, 0x9f, 0xee, 0x31, 0xdc, 0x2d, 0xfe,
	0x9e, 0x9d, 0x7e, 0x5f, 0x33, 0x53, 0x3b, 0xb9, 0xd8, 0xcc, 0x9c, 0xde, 0x2c, 0xf6, 0xa1, 0x35,
	0x3f, 0xfc, 0x5f, 0x64, 0x3d, 0x4b, 0x7f, 0xdd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xf3, 0x38,
	0x11, 0x97, 0x03, 0x00, 0x00,
}
